[package]
name = "dump-dvb"
version = "0.1.0"
edition = "2021"

[dependencies]

serde_json = "1.0"
serde = {version = "*", features = ["derive"]}
chrono = {version = "0.4", features = [ "serde" ]}

diesel = { version = "1", features = ["postgres", "r2d2", "uuidv07", "chrono"]}
uuid = {version = "=0.8.1", features = ["serde", "v4"]}
dotenv = "*"

tonic = "0.7"
prost = "0.10"

csv = "1.1"

[build-dependencies]
tonic-build = "0.7"
