[package]
name = "dump-dvb"
version = "0.5.1"
edition = "2021"

[dependencies]

serde_json = "1.0"
serde = {version = "*", features = ["derive"]}
chrono = {version = "0", features = [ "serde" ]}

diesel = { version = "2", features = ["postgres", "r2d2", "chrono", "uuid"]}
uuid = {version = "1", features = ["serde", "v4"]}
dotenv = "*"

tonic = "0.7"
prost = "0.10"

csv = "1"
struct-field-names-as-array = "0.1"
num-traits = "0.2"
num-derive = "0.3"
pbkdf2 = "0.10"
diesel_codegen = "*"
rand = "*"
log = "*"
regex = "*"

[build-dependencies]
tonic-build = "0.7"
